version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "46032:46032"
    volumes:
      - ./shared_volume:/mnt/shared
    restart: unless-stopped


networks:
  default:
      name: lan_nasa
