version: '3.8'

services:
  app:
    image: pyso/nasa:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./shared_volume:/app/uploads
    restart: unless-stopped

networks:
  default:
      name: lan_nasa
